on: 
  pull_request:
    paths:
      - 'contributions/demo/**'

jobs:
  youtube-checker:
    runs-on: ubuntu-latest
    name: Checking length of potential youtube-video
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get modified files
        run: |
          git fetch --quiet
          changed=$(git diff ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} --name-only)
          changed="${changed//'%'/'%25'}"
          changed="${changed//$'\n'/'%0A'}"
          changed="${changed//$'\r'/'%0D'}"
          echo "::set-output name=files::$changed"
        id: git-command
      - name: Youtube Checker Step
        uses: heeenkie/youtube-link-checker-action@v1
        id: checker
        with:
          file-path: ${{ steps.git-command.outputs.files}}
          youtube-api-key: ${{ secrets.YOUTUBE_API_KEY }}
          min-length: '180'
          max-length: '300'
