on: [pull_request]
    #paths:
    #  - 'contributions/demo/'

jobs:
  youtube-checker:
    runs-on: ubuntu-latest
    name: Checking length of potential youtube-video
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get modified files
        run: |
          git fetch --quiet
          echo "::set-output name=changed-files::$(git diff ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} --name-only)"
        id: git-command
      - name: Youtube Checker Step
        uses: ./
        id: checker
        with:
          file-path: ${{ steps.git-command.outputs.changed-files}}