on:
  push:
    paths:
      - 'contributions/demo/'

jobs:
  youtube-checker:
    runs-on: ubuntu-latest
    name: Checking length of potential youtube-video
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: changed
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Youtube Checker Step
        uses: ./
        id: checker
        with:
          file-path: ${{ steps.changed.outputs.modified }}