on: [pull_request]
    #paths:
    #  - 'contributions/demo/'

jobs:
  youtube-checker:
    runs-on: ubuntu-latest
    name: Checking length of potential youtube-video
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get modified files
        run: |
          echo "::set-output name=changed-files::$(git diff ${{ github.sha }} ${{ github.event.pull_request.base.sha }} --name-only)"
        #run: ::set-output name=changed-files::$(git diff --relative --name-only)
        id: git-command
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
          #github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Youtube Checker Step
        uses: ./
        id: checker
        with:
          file-path: ${{ steps.git-command.outputs.changed-files}}